// DataFetchContext

export const GET_WEATHER_LOADING = "GET_WEATHER_LOADING";
export const GET_WEATHER = "GET_WEATHER";
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR";

export const GET_POLLUTION_LOADING = "GET_POLLUTION_LOADING";
export const GET_POLLUTION = "GET_POLLUTION";
export const GET_POLLUTION_ERROR = "GET_POLLUTION_ERROR";

export const GET_GEOGRAPHIC_DATA = "GET_GEOGRAPHIC_DATA";
export const GET_GEOGRAPHIC_DATA_ERROR = "GET_GEOGRAPHIC_DATA_ERROR";

export const SET_GEOGRAPHIC_DATA = "SET_GEOGRAPHIC_DATA";

// SavedSearchesContext

export const SAVE_SEARCH = "SAVE_SEARCH";
export const DELETE_SEARCH = "DELETE_SEARCH";

export const SET_HEIGHT_SAVED_SEARCHES = "SET_HEIGHT_SAVED_SEARCHES";
